# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4110a1539ffccb454b5f5927e8b0893d96b898a315851403e97fcbc27ece563b00c592ac23a02446e3ae032dff55ac4f2c80670222b6ca53b2788be6fc4f508

test:
  secret_key_base: 1c24af21120c51bf8e884aefee71c91cbaa10722f476b97419faab5f040c251fc74579e6883e03fdfa2b280eaad7ece39b45d76830c0684de396d05f09565ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
